-- ============================================================================
-- שאילתת ייצוא סכימה מלאה — כדורגל גניגרי ושות'
-- ============================================================================
-- שאילתה לקריאה בלבד (לא משנה כלום) שמייצרת מחדש, מתוך פנקסי המערכת של
-- Postgres עצמו (pg_catalog), את כל ה-CREATE TABLE/INDEX/EXTENSION המקוריים
-- של הפרויקט — כולל הדברים שמעולם לא תועדו כאן כי נוצרו לפני תחילת העבודה
-- הזו (טיפוסי עמודות, NOT NULL, ברירות מחדל, PRIMARY KEY, FOREIGN KEY,
-- UNIQUE, אינדקסים). זה סוגר את הפער שהיה מתועד עד עכשיו ב-README.md
-- ("לא נאספה כאן הגדרת הטבלאות המקורית").
--
-- לא כולל RPC functions (יש כבר ב-functions.sql) או מדיניות RLS (יש כבר
-- ב-policies.sql) — רק את מה שבאמת חסר: מבנה הטבלאות עצמו.
--
-- איך משתמשים: להריץ פעם אחת ב-SQL Editor של Supabase, להעתיק את כל
-- התוצאה (עמודת stmt, שורה אחר שורה, מלמעלה למטה), ולשמור/לשלוח כדי שתהפוך
-- לקובץ גיבוי מלא וקבוע (ר' README.md). מומלץ לחזור על זה מדי פעם שיש שינוי
-- סכימה משמעותי, לא רק פעם אחת.
-- ============================================================================

with cols as (
  select
    c.relname as table_name,
    string_agg(
      format('  %I %s%s%s%s',
        a.attname,
        pg_catalog.format_type(a.atttypid, a.atttypmod),
        case a.attidentity when 'd' then ' generated by default as identity' when 'a' then ' generated always as identity' else '' end,
        case when a.attnotnull then ' not null' else '' end,
        case when d.adbin is not null and a.attidentity = '' then ' default ' || pg_get_expr(d.adbin, d.adrelid) else '' end
      ),
      E',\n' order by a.attnum
    ) as cols_sql
  from pg_attribute a
  join pg_class c on c.oid = a.attrelid
  join pg_namespace n on n.oid = c.relnamespace
  left join pg_attrdef d on d.adrelid = c.oid and d.adnum = a.attnum
  where n.nspname = 'public' and c.relkind = 'r' and a.attnum > 0 and not a.attisdropped
  group by c.relname
),
cons as (
  select conrelid::regclass::text as table_name,
    string_agg('  constraint ' || quote_ident(conname) || ' ' || pg_get_constraintdef(oid), E',\n' order by contype, conname) as cons_sql
  from pg_constraint
  where connamespace = 'public'::regnamespace and conrelid <> 0
  group by conrelid
),
tables_ddl as (
  select cols.table_name, 1 as ord,
    format('create table if not exists %I (\n%s%s\n);', cols.table_name,
      cols.cols_sql, coalesce(E',\n' || cons.cons_sql, ''))
    as stmt
  from cols left join cons on cons.table_name = cols.table_name
),
indexes_ddl as (
  select indexname as table_name, 2 as ord, indexdef || ';' as stmt
  from pg_indexes
  where schemaname = 'public'
    and indexname not in (select conname from pg_constraint where connamespace = 'public'::regnamespace)
),
ext_ddl as (
  select extname as table_name, 0 as ord, format('create extension if not exists %I;', extname) as stmt
  from pg_extension
  where extname <> 'plpgsql'
)
select stmt from (
  select * from ext_ddl
  union all select * from tables_ddl
  union all select * from indexes_ddl
) x
order by ord, table_name;
