-- ============================================================================
-- כדורגל גניגרי ושות' — עמודות שנוספו לסכימה הקיימת
-- ============================================================================
-- אלה תוספות על טבלאות שכבר היו קיימות לפני הפרויקט הזה. הגדרת הטבלאות
-- המקורית (CREATE TABLE, טיפוסים, אילוצים) לא תועדה כאן כי לא הועברה
-- אלינו — ר' הערה ב-README.md באותה תיקייה.
-- ============================================================================

-- מסמן אם שחקן הגיע בפועל למשחק (לא רק נרשם) — קובע עדיפות "מתמיד" בהרשמות עתידיות
alter table registrations add column if not exists attended boolean default false;

-- נועל את נתוני הנוכחות של משחק ספציפי: רק משחקים נעולים נספרים בעדיפות
-- "מתמיד" (ר' get_my_identity/tierRank ב-index.html) — מאפשר לאדמין לערוך
-- סימוני נוכחות בלי שזה משפיע על אף אחד, ורק לאחר נעילה זה "נצרב"
alter table games add column if not exists attendance_locked boolean default false;

-- טבלה חדשה: לוג שגיאות קליינט (ר' log_client_error ב-functions.sql,
-- ErrorBoundary/window.onerror/callAdmin ב-index.html). RLS מופעל בלי אף
-- מדיניות — write-only דרך ה-RPC בלבד, לא ניתנת לקריאה מהדפדפן (כמו
-- settings/login_attempts).
create table if not exists client_errors (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  message text,
  stack text,
  user_agent text,
  url text,
  context text
);
alter table client_errors enable row level security;
