-- ============================================================================
-- כדורגל גניגרי ושות' — גיבוי סכימה מלאה (2026-09-15)
-- ============================================================================
-- תוצר הרצה בפועל של export_full_schema.sql מול ה-Supabase החי של הפרויקט.
-- זה סוגר את הפער שהיה מתועד ב-README.md: הגדרת הטבלאות המקורית מעולם לא
-- נאספה עד עכשיו. יחד עם functions.sql + policies.sql + schema_additions.sql
-- (שמתעדים את השכבות שנוספו מעל הבסיס הזה), זה מקור אמת מלא לשחזור מאפס.
--
-- שני שינויים ידניים קלים ביחס לפלט הגולמי של השאילתה:
--   1. תוקן פורמט (השאילתה עצמה החזירה "\n" מילולי במקום ירידת שורה בתחילת/
--      סוף כל create table — תוקן גם ב-export_full_schema.sql עצמו, ר' שם).
--   2. נוספו שתי הגדרות ה-sequence הישנות (login_attempts, registrations) —
--      אלה עמודות "serial" קלאסיות (לא identity), אז ה-DEFAULT שלהן מפנה
--      ל-sequence בשם מפורש שחייב להיווצר קודם, אחרת ה-CREATE TABLE נכשל.
--
-- סדר ההרצה כאן חשוב: games לפני registrations (יש FK ביניהם).
-- ============================================================================

-- ---- Extensions ----
create extension if not exists pg_stat_statements;
create extension if not exists pgcrypto;
create extension if not exists supabase_vault;
create extension if not exists "uuid-ossp";

-- ---- Sequences (לעמודות serial ישנות, לפני הטבלאות שמשתמשות בהן) ----
create sequence if not exists login_attempts_id_seq;
create sequence if not exists registrations_id_seq;

-- ---- Tables ----

create table if not exists admin_audit_log (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  actor_role text,
  actor_identifier text,
  action text not null,
  details jsonb,
  constraint admin_audit_log_pkey primary key (id)
);

create table if not exists admin_invites (
  id text not null,
  player_phone text not null,
  code text not null,
  used boolean default false,
  created_at timestamp with time zone default now(),
  constraint admin_invites_pkey primary key (id)
);

create table if not exists admin_pin_resets (
  id text not null,
  admin_phone text not null,
  code text not null,
  used boolean default false,
  created_at timestamp with time zone default now(),
  constraint admin_pin_resets_pkey primary key (id)
);

create table if not exists admin_requests (
  id text not null,
  name text not null,
  phone text not null,
  created_at timestamp with time zone default now(),
  constraint admin_requests_pkey primary key (id),
  constraint admin_requests_phone_key unique (phone)
);

create table if not exists admins (
  id text not null,
  name text not null,
  phone text not null,
  created_at timestamp with time zone default now(),
  pin text,
  constraint admins_pkey primary key (id),
  constraint admins_phone_key unique (phone)
);

create table if not exists client_errors (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  message text,
  stack text,
  user_agent text,
  url text,
  context text,
  constraint client_errors_pkey primary key (id)
);

create table if not exists games (
  id text not null,
  kickoff bigint not null,
  opens_at bigint not null,
  published boolean default false,
  roster_published boolean default false,
  created_at timestamp with time zone default now(),
  attendance_locked boolean default false,
  constraint games_pkey primary key (id)
);

create table if not exists login_attempts (
  id bigint not null default nextval('login_attempts_id_seq'::regclass),
  kind text not null,
  key text not null,
  created_at timestamp with time zone default now(),
  constraint login_attempts_pkey primary key (id)
);

create table if not exists player_requests (
  id text not null,
  name text not null,
  phone text not null,
  created_at timestamp with time zone default now(),
  status text default 'pending'::text,
  decided_at timestamp with time zone,
  email text,
  auth_user_id uuid,
  constraint player_requests_pkey primary key (id),
  constraint player_requests_phone_key unique (phone)
);

create table if not exists players (
  id text not null,
  name text not null,
  phone text not null,
  created_at timestamp with time zone default now(),
  is_ganigari boolean default false,
  is_vatik boolean default false,
  approved_at timestamp with time zone default now(),
  email text,
  auth_user_id uuid,
  constraint players_pkey primary key (id),
  constraint players_auth_user_id_key unique (auth_user_id),
  constraint players_phone_key unique (phone)
);

create table if not exists registrations (
  id bigint not null default nextval('registrations_id_seq'::regclass),
  game_id text,
  player_id text not null,
  ts bigint not null,
  device_token text,
  device_id text,
  attended boolean default false,
  constraint registrations_pkey primary key (id),
  constraint registrations_game_id_player_id_key unique (game_id, player_id),
  constraint registrations_game_id_fkey foreign key (game_id) references games(id) on delete cascade
);

create table if not exists settings (
  id integer not null default 1,
  admin_pw text,
  super_pw text,
  super_phone text,
  constraint settings_pkey primary key (id)
);
