-- ============================================================================
-- כדורגל גניגרי ושות' — עמודות שנוספו לסכימה הקיימת
-- ============================================================================
-- אלה תוספות על טבלאות שכבר היו קיימות לפני הפרויקט הזה. הגדרת הטבלאות
-- המקורית (CREATE TABLE, טיפוסים, אילוצים) לא תועדה כאן כי לא הועברה
-- אלינו — ר' הערה ב-README.md באותה תיקייה.
-- ============================================================================

-- מסמן אם שחקן הגיע בפועל למשחק (לא רק נרשם) — קובע עדיפות "מתמיד" בהרשמות עתידיות
alter table registrations add column if not exists attended boolean default false;

-- שם תצוגה לאורח חד-פעמי שהאדמין הוסיף ידנית למשחק ספציפי (ר' migrations/0008
-- ו-admin_add_guest_registration). player_id של אורח הוא ערך סינתטי (guest_<uuid>)
-- ולא מפנה לשורה אמיתית ב-players — guest_name הוא השם שמוצג במקומו בכל מקום
-- שבו הקוד מציג שם על בסיס player_id.
alter table registrations add column if not exists guest_name text;

-- נועל את נתוני הנוכחות של משחק ספציפי: רק משחקים נעולים נספרים בעדיפות
-- "מתמיד" (ר' get_my_identity/tierRank ב-index.html) — מאפשר לאדמין לערוך
-- סימוני נוכחות בלי שזה משפיע על אף אחד, ורק לאחר נעילה זה "נצרב"
alter table games add column if not exists attendance_locked boolean default false;

-- טבלה חדשה: לוג שגיאות קליינט (ר' log_client_error ב-functions.sql,
-- ErrorBoundary/window.onerror/callAdmin ב-index.html). RLS מופעל בלי אף
-- מדיניות — write-only דרך ה-RPC בלבד, לא ניתנת לקריאה מהדפדפן (כמו
-- settings/login_attempts).
create table if not exists client_errors (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  message text,
  stack text,
  user_agent text,
  url text,
  context text
);
alter table client_errors enable row level security;

-- טבלה חדשה: לוג פעולות ניהול (ר' log_admin_action ב-functions.sql). כל
-- פעולת ניהול-על (ולחלק מהפעולות המשותפות עם מנהל רגיל) כותבת לכאן מי
-- ביצע מה ומתי — כדי שטעות/מחיקה/שינוי אפשר יהיה לשחזר "מי עשה את זה".
-- RLS מופעל בלי אף מדיניות — חסום לגמרי מגישה ציבורית (כמו client_errors/
-- settings/login_attempts), נקרא רק דרך שאילתה ישירה ב-Supabase Dashboard.
create table if not exists admin_audit_log (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  actor_role text,        -- 'admin' | 'super'
  actor_identifier text,  -- טלפון המנהל, או 'super' (אין הבחנה בין משתמשי-על — סיסמה משותפת אחת)
  action text not null,   -- שם הפונקציה שביצעה את הפעולה
  details jsonb           -- פרטי הפעולה (לעולם לא כולל סיסמאות/PIN)
);
alter table admin_audit_log enable row level security;

-- טבלה חדשה: סימון "לא מגיע" מפורש של שחקן למשחק (ר' decline_game/
-- cancel_own_decline ב-functions.sql, GameCard ב-index.html) — נפרדת
-- לגמרי מ-registrations (שמייצגת "רוצה מקום"), כדי לא לערבב שני מושגים
-- שונים. SELECT פתוח לכולם (כמו registrations) — כל כתיבה רק דרך RPC.
create table if not exists game_declines (
  id bigint generated by default as identity primary key,
  game_id text not null references games(id) on delete cascade,
  player_id text not null,
  ts bigint not null,
  constraint game_declines_game_id_player_id_key unique (game_id, player_id)
);
alter table game_declines enable row level security;
