-- ============================================================================
-- Migration 0002 — Client-side error logging (2026-09-14)
-- ============================================================================
-- מוסיף טבלת client_errors (write-only, בלי מדיניות SELECT — כמו settings/
-- login_attempts) ופונקציית RPC log_client_error שכל קליינט יכול לקרוא לה
-- בלי אימות כדי לדווח שגיאה. תומך ב-ErrorBoundary/window.onerror/callAdmin
-- החדשים ב-index.html.
-- ============================================================================

create table if not exists client_errors (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  message text,
  stack text,
  user_agent text,
  url text,
  context text
);
alter table client_errors enable row level security;
-- בכוונה בלי אף policy — חסום לגמרי לקריאה/כתיבה ישירה, רק דרך ה-RPC למטה.

create or replace function log_client_error(
  p_message text, p_stack text, p_user_agent text, p_url text, p_context text
) returns void language plpgsql security definer as $$
begin
  insert into client_errors (message, stack, user_agent, url, context)
    values (left(p_message,2000), left(p_stack,4000), left(p_user_agent,500), left(p_url,500), left(p_context,200));
end; $$;

grant execute on function log_client_error(text,text,text,text,text) to anon, authenticated;
