-- ============================================================================
-- Migration 0003 — Admin action audit log (2026-09-14)
-- ============================================================================
-- מוסיף טבלת admin_audit_log (write-only, בלי מדיניות SELECT — כמו
-- settings/login_attempts/client_errors) ופונקציית עזר log_admin_action,
-- וקורא לה מכל פונקציות ה-RPC הניהוליות הקיימות (אישור/דחיית בקשות, ניהול
-- שחקנים, ניהול משחקים/הרשמות/נוכחות, עדכון הגדרות) — כדי שאפשר יהיה לדעת
-- "מי עשה מה ומתי" אחרי טעות/מחיקה/שינוי. לעולם לא נרשמת סיסמה/PIN ללוג.
--
-- קובץ זה הוא ה-migration ההיסטורי; supabase/schema_additions.sql ו-
-- supabase/functions.sql מעודכנים במקביל כדי לשקף את אותו שינוי ב"תמונת
-- המצב הנוכחית" (ר' README.md).
-- ============================================================================

-- ---- טבלה ----
create table if not exists admin_audit_log (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  actor_role text,
  actor_identifier text,
  action text not null,
  details jsonb
);
alter table admin_audit_log enable row level security;
-- בכוונה בלי אף policy — חסום לגמרי לקריאה/כתיבה ישירה, רק דרך log_admin_action.

-- ---- פונקציית עזר ----
create or replace function log_admin_action(p_role text, p_actor text, p_action text, p_details jsonb)
returns void language plpgsql security definer as $$
begin
  insert into admin_audit_log (actor_role, actor_identifier, action, details)
    values (p_role, p_actor, p_action, p_details);
end; $$;
revoke all on function log_admin_action(text,text,text,jsonb) from public;

-- ---- עדכון הפונקציות הקיימות: מוסיפות שורת perform log_admin_action(...)
-- לפני כל return מוצלח. שאר גוף הפונקציה זהה למה שהיה קיים (ר' functions.sql
-- להיסטוריה המלאה + הסברים על כל פונקציה). כל הפונקציות משתמשות ב-
-- create or replace, בטוח להריץ מחדש.

create or replace function approve_player_request(
  input_request_id text, input_is_ganigari boolean, input_is_vatik boolean, input_pw text
) returns text language plpgsql security definer as $$
declare v_role text; r record;
begin
  v_role := require_admin(input_pw, null, null);
  if v_role <> 'super' then raise exception 'not_authorized'; end if;
  select * into r from player_requests where id = input_request_id;
  if r is null then return 'not_found'; end if;
  if exists (select 1 from players where phone = r.phone) then return 'phone_taken'; end if;
  insert into players (id, name, phone, is_ganigari, is_vatik, email, auth_user_id)
    values ('p'||floor(extract(epoch from now())*1000)::text, r.name, r.phone, input_is_ganigari, input_is_vatik, r.email, r.auth_user_id);
  delete from player_requests where id = input_request_id;
  perform log_admin_action('super', 'super', 'approve_player_request', jsonb_build_object('request_id', input_request_id, 'name', r.name, 'phone', r.phone, 'is_ganigari', input_is_ganigari, 'is_vatik', input_is_vatik));
  return 'ok';
end; $$;

create or replace function reject_player_request(input_request_id text, input_pw text)
returns boolean language plpgsql security definer as $$
declare v_role text;
begin
  v_role := require_admin(input_pw, null, null);
  if v_role <> 'super' then raise exception 'not_authorized'; end if;
  update player_requests set status='rejected', decided_at = now() where id = input_request_id;
  perform log_admin_action('super', 'super', 'reject_player_request', jsonb_build_object('request_id', input_request_id));
  return true;
end; $$;

create or replace function reconsider_player_request(input_request_id text, input_pw text)
returns boolean language plpgsql security definer as $$
declare v_role text;
begin
  v_role := require_admin(input_pw, null, null);
  if v_role <> 'super' then raise exception 'not_authorized'; end if;
  update player_requests set status='pending', decided_at = null where id = input_request_id;
  perform log_admin_action('super', 'super', 'reconsider_player_request', jsonb_build_object('request_id', input_request_id));
  return true;
end; $$;

create or replace function remove_admin(input_admin_id text, input_pw text)
returns boolean language plpgsql security definer as $$
declare v_role text;
begin
  v_role := require_admin(input_pw, null, null);
  if v_role <> 'super' then raise exception 'not_authorized'; end if;
  delete from admins where id = input_admin_id;
  perform log_admin_action('super', 'super', 'remove_admin', jsonb_build_object('admin_id', input_admin_id));
  return true;
end; $$;

create or replace function admin_add_player(input_name text, input_phone text, input_is_ganigari boolean, input_is_vatik boolean, input_pw text)
returns text language plpgsql security definer as $$
declare v_role text;
begin
  v_role := require_admin(input_pw, null, null);
  if v_role <> 'super' then raise exception 'not_authorized'; end if;
  if exists (select 1 from players where phone = input_phone) then return 'phone_taken'; end if;
  insert into players (id, name, phone, is_ganigari, is_vatik)
    values ('p'||floor(extract(epoch from now())*1000)::text, input_name, input_phone, input_is_ganigari, input_is_vatik);
  perform log_admin_action('super', 'super', 'admin_add_player', jsonb_build_object('name', input_name, 'phone', input_phone, 'is_ganigari', input_is_ganigari, 'is_vatik', input_is_vatik));
  return 'ok';
end; $$;

create or replace function admin_delete_player(input_player_id text, input_pw text)
returns boolean language plpgsql security definer as $$
declare v_role text; v_name text;
begin
  v_role := require_admin(input_pw, null, null);
  if v_role <> 'super' then raise exception 'not_authorized'; end if;
  select name into v_name from players where id = input_player_id;
  delete from registrations where player_id = input_player_id;
  delete from players where id = input_player_id;
  perform log_admin_action('super', 'super', 'admin_delete_player', jsonb_build_object('player_id', input_player_id, 'name', v_name));
  return true;
end; $$;

create or replace function admin_set_player_ganigari(input_player_id text, input_value boolean, input_pw text)
returns boolean language plpgsql security definer as $$
declare v_role text;
begin
  v_role := require_admin(input_pw, null, null);
  if v_role <> 'super' then raise exception 'not_authorized'; end if;
  update players set is_ganigari = input_value where id = input_player_id;
  perform log_admin_action('super', 'super', 'admin_set_player_ganigari', jsonb_build_object('player_id', input_player_id, 'value', input_value));
  return true;
end; $$;

create or replace function admin_set_player_vatik(input_player_id text, input_value boolean, input_pw text)
returns boolean language plpgsql security definer as $$
declare v_role text;
begin
  v_role := require_admin(input_pw, null, null);
  if v_role <> 'super' then raise exception 'not_authorized'; end if;
  update players set is_vatik = input_value where id = input_player_id;
  perform log_admin_action('super', 'super', 'admin_set_player_vatik', jsonb_build_object('player_id', input_player_id, 'value', input_value));
  return true;
end; $$;

create or replace function admin_update_player_name(input_player_id text, input_name text, input_pw text)
returns boolean language plpgsql security definer as $$
declare v_role text;
begin
  v_role := require_admin(input_pw, null, null);
  if v_role <> 'super' then raise exception 'not_authorized'; end if;
  update players set name = input_name where id = input_player_id;
  perform log_admin_action('super', 'super', 'admin_update_player_name', jsonb_build_object('player_id', input_player_id, 'new_name', input_name));
  return true;
end; $$;

create or replace function admin_update_player_phone(input_player_id text, input_phone text, input_pw text)
returns text language plpgsql security definer as $$
declare v_role text;
begin
  v_role := require_admin(input_pw, null, null);
  if v_role <> 'super' then raise exception 'not_authorized'; end if;
  if exists (select 1 from players where phone = input_phone and id <> input_player_id) then return 'phone_taken'; end if;
  update players set phone = input_phone where id = input_player_id;
  perform log_admin_action('super', 'super', 'admin_update_player_phone', jsonb_build_object('player_id', input_player_id, 'new_phone', input_phone));
  return 'ok';
end; $$;

create or replace function admin_update_player_email(input_player_id text, input_email text, input_pw text)
returns boolean language plpgsql security definer as $$
declare v_role text;
begin
  v_role := require_admin(input_pw, null, null);
  if v_role <> 'super' then raise exception 'not_authorized'; end if;
  update players set email = input_email where id = input_player_id;
  perform log_admin_action('super', 'super', 'admin_update_player_email', jsonb_build_object('player_id', input_player_id, 'new_email', input_email));
  return true;
end; $$;

create or replace function admin_create_game(input_kickoff bigint, input_opens_at bigint, input_pw text, input_phone text, input_pin text)
returns text language plpgsql security definer as $$
declare v_role text; v_game_id text;
begin
  v_role := require_admin(input_pw, input_phone, input_pin);
  v_game_id := 'g'||floor(extract(epoch from now())*1000)::text;
  insert into games (id, kickoff, opens_at, published, roster_published)
    values (v_game_id, input_kickoff, input_opens_at, false, false);
  perform log_admin_action(v_role, coalesce(input_phone,'super'), 'admin_create_game', jsonb_build_object('game_id', v_game_id, 'kickoff', input_kickoff, 'opens_at', input_opens_at));
  return 'ok';
end; $$;

create or replace function admin_set_game_published(input_game_id text, input_published boolean, input_pw text, input_phone text, input_pin text)
returns boolean language plpgsql security definer as $$
declare v_role text;
begin
  v_role := require_admin(input_pw, input_phone, input_pin);
  update games set published = input_published where id = input_game_id;
  perform log_admin_action(v_role, coalesce(input_phone,'super'), 'admin_set_game_published', jsonb_build_object('game_id', input_game_id, 'published', input_published));
  return true;
end; $$;

create or replace function admin_set_roster_published(input_game_id text, input_roster_published boolean, input_pw text, input_phone text, input_pin text)
returns boolean language plpgsql security definer as $$
declare v_role text;
begin
  v_role := require_admin(input_pw, input_phone, input_pin);
  update games set roster_published = input_roster_published where id = input_game_id;
  perform log_admin_action(v_role, coalesce(input_phone,'super'), 'admin_set_roster_published', jsonb_build_object('game_id', input_game_id, 'roster_published', input_roster_published));
  return true;
end; $$;

create or replace function admin_delete_game(input_game_id text, input_pw text, input_phone text, input_pin text)
returns boolean language plpgsql security definer as $$
declare v_role text;
begin
  v_role := require_admin(input_pw, input_phone, input_pin);
  delete from registrations where game_id = input_game_id;
  delete from games where id = input_game_id;
  perform log_admin_action(v_role, coalesce(input_phone,'super'), 'admin_delete_game', jsonb_build_object('game_id', input_game_id));
  return true;
end; $$;

create or replace function admin_set_registration_ts(input_game_id text, input_player_id text, input_ts bigint, input_pw text, input_phone text, input_pin text)
returns boolean language plpgsql security definer as $$
declare v_role text;
begin
  v_role := require_admin(input_pw, input_phone, input_pin);
  update registrations set ts = input_ts where game_id = input_game_id and player_id = input_player_id;
  perform log_admin_action(v_role, coalesce(input_phone,'super'), 'admin_set_registration_ts', jsonb_build_object('game_id', input_game_id, 'player_id', input_player_id, 'ts', input_ts));
  return true;
end; $$;

create or replace function admin_add_registration(
  input_game_id text, input_player_id text, input_pw text default null, input_phone text default null, input_pin text default null
) returns boolean language plpgsql security definer as $$
declare v_role text;
begin
  v_role := require_admin(input_pw, input_phone, input_pin);
  insert into registrations (game_id, player_id, ts) values (input_game_id, input_player_id, (extract(epoch from now())*1000)::bigint);
  perform log_admin_action(v_role, coalesce(input_phone,'super'), 'admin_add_registration', jsonb_build_object('game_id', input_game_id, 'player_id', input_player_id));
  return true;
end; $$;

create or replace function admin_remove_registration(
  input_game_id text, input_player_id text, input_pw text default null, input_phone text default null, input_pin text default null
) returns boolean language plpgsql security definer as $$
declare v_role text;
begin
  v_role := require_admin(input_pw, input_phone, input_pin);
  delete from registrations where game_id=input_game_id and player_id=input_player_id;
  perform log_admin_action(v_role, coalesce(input_phone,'super'), 'admin_remove_registration', jsonb_build_object('game_id', input_game_id, 'player_id', input_player_id));
  return true;
end; $$;

create or replace function admin_set_attendance(
  input_game_id text, input_player_id text, input_attended boolean,
  input_pw text default null, input_phone text default null, input_pin text default null
) returns boolean language plpgsql security definer as $$
declare v_role text;
begin
  v_role := require_admin(input_pw, input_phone, input_pin);
  update registrations set attended = input_attended where game_id = input_game_id and player_id = input_player_id;
  perform log_admin_action(v_role, coalesce(input_phone,'super'), 'admin_set_attendance', jsonb_build_object('game_id', input_game_id, 'player_id', input_player_id, 'attended', input_attended));
  return true;
end; $$;

create or replace function admin_set_attendance_locked(
  input_game_id text, input_locked boolean,
  input_pw text default null, input_phone text default null, input_pin text default null
) returns boolean language plpgsql security definer as $$
declare v_role text;
begin
  v_role := require_admin(input_pw, input_phone, input_pin);
  update games set attendance_locked = input_locked where id = input_game_id;
  perform log_admin_action(v_role, coalesce(input_phone,'super'), 'admin_set_attendance_locked', jsonb_build_object('game_id', input_game_id, 'locked', input_locked));
  return true;
end; $$;

create or replace function update_settings_secure(
  current_super_pw text, new_super_pw text, new_super_phone text
) returns boolean
language plpgsql security definer as $$
declare v_email text; v_result boolean;
begin
  select lower(coalesce(auth.jwt() ->> 'email', '')) into v_email;
  if v_email is distinct from 'nadavfichman@gmail.com' then
    raise exception 'email_verification_required';
  end if;
  v_result := update_settings(
    current_super_pw => current_super_pw,
    new_super_pw => new_super_pw,
    new_super_phone => new_super_phone
  );
  if v_result then
    perform log_admin_action('super', 'super', 'update_settings_secure', jsonb_build_object('changed_password', new_super_pw is not null, 'changed_phone', new_super_phone is not null));
  end if;
  return v_result;
end; $$;
