-- ============================================================================
-- Migration 0006 — "Not attending" (declines) for games (2026-09-15)
-- ============================================================================
-- מוסיף אפשרות לשחקן לסמן במפורש "לא אגיע" למשחק (לא רק לא להירשם) —
-- כדי שלאדמין יהיה נתון אמיתי כמה אנשים בפועל לא מגיעים (למשל 10 סירובים
-- מפורשים זה איתות ברור להזמין חברים מבחוץ). ר' GameCard/AdminGameRow
-- ב-index.html.
--
-- game_declines נפרדת לגמרי מ-registrations (מושג שונה: "לא רוצה מקום",
-- לא "רוצה מקום"). שני המצבים הדדיים: decline_game מוחקת הרשמה קיימת,
-- register_for_game מוחקת decline קיים.
-- ============================================================================

create table if not exists game_declines (
  id bigint generated by default as identity primary key,
  game_id text not null references games(id) on delete cascade,
  player_id text not null,
  ts bigint not null,
  constraint game_declines_game_id_player_id_key unique (game_id, player_id)
);
alter table game_declines enable row level security;

drop policy if exists "game_declines select" on game_declines;
create policy "game_declines select" on game_declines for select to public using (true);

create or replace function decline_game(input_game_id text, input_player_id text)
returns text language plpgsql security definer as $$
declare v_uid uuid;
begin
  v_uid := auth.uid();
  if v_uid is null or not exists (select 1 from players where id=input_player_id and auth_user_id=v_uid) then
    return 'not_authorized';
  end if;
  delete from registrations where game_id=input_game_id and player_id=input_player_id;
  insert into game_declines (game_id, player_id, ts) values (input_game_id, input_player_id, (extract(epoch from now())*1000)::bigint)
    on conflict (game_id, player_id) do update set ts = excluded.ts;
  return 'ok';
end; $$;

create or replace function cancel_own_decline(input_game_id text, input_player_id text)
returns boolean language plpgsql security definer as $$
declare v_uid uuid;
begin
  v_uid := auth.uid();
  if v_uid is null or not exists (select 1 from players where id=input_player_id and auth_user_id=v_uid) then
    return false;
  end if;
  delete from game_declines where game_id=input_game_id and player_id=input_player_id;
  return found;
end; $$;

-- מעודכנת כדי לנקות decline קיים בעת הרשמה (ר' הערה למעלה על הדדיות)
create or replace function register_for_game(input_game_id text, input_player_id text)
returns text language plpgsql security definer as $$
declare v_uid uuid; already_registered boolean;
begin
  v_uid := auth.uid();
  if v_uid is null or not exists (select 1 from players where id=input_player_id and auth_user_id=v_uid) then
    return 'not_authorized';
  end if;
  select exists(select 1 from registrations where game_id=input_game_id and player_id=input_player_id) into already_registered;
  if already_registered then return 'already_registered'; end if;
  delete from game_declines where game_id=input_game_id and player_id=input_player_id;
  insert into registrations (game_id, player_id, ts) values (input_game_id, input_player_id, (extract(epoch from now())*1000)::bigint);
  return 'ok';
end; $$;
